services:
  receiver:
    build: .
    image: udp-tester
    container_name: udp_receiver
    network_mode: "host"
    volumes:
      - .:/app
    environment:
      - UDP_PORT=5005
    command: python receiver.py
    restart: unless-stopped

  sender:
    build: .
    image: udp-tester
    container_name: udp_sender
    network_mode: "host"
    volumes:
      - .:/app
    environment:
      - TARGET_IP=10.118.91.71   # REPLACE WITH VEHICLE IP ADRESS
      - UDP_PORT=5005
    command: python sender.py