version: '3.8'

services:
  ws-node:
    build: .
    container_name: websocket_research
    network_mode: "host" # Para facilitar comunicación en red local
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
    volumes:
      - ./app:/app