services:
  camera-streamer:
    build: .
    container_name: rtp_camera_service
    network_mode: "host"
    devices:
      - "/dev/video3:/dev/video3"
      - "/dev/video4:/dev/video4"
      - "/dev/media1:/dev/media1"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1